# Generated by Django 5.2.9 on 2025-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('lien_demo', models.URLField(blank=True, null=True)),
                ('lien_github', models.URLField(blank=True, null=True)),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_publication'],
            },
        ),
    ]
